version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: movie_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J@nc0k12
      POSTGRES_DB: bioskop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: